# Shared tasks for all Node/TypeScript projects
# https://moonrepo.dev/docs/config/tasks

inheritedBy:
  languages: ['javascript', 'typescript']

tasks:
  build:
    command: 'pnpm run build'
    deps:
      - '^:build'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - 'package.json'
    outputs:
      - 'dist'

  format-check:
    command: 'prettier --check . --ignore-path $workspaceRoot/.prettierignore'
    inputs:
      - '**/*'

  format:
    command: 'prettier --write . --ignore-path $workspaceRoot/.prettierignore'
    inputs:
      - '**/*'

  lint:
    script: 'prettier --check . --ignore-path $workspaceRoot/.prettierignore && eslint --no-error-on-unmatched-pattern .'
    inputs:
      - '**/*'

  typecheck:
    command: 'tsc -b'
    deps:
      - '^:build'
    inputs:
      - '**/*'

  test:
    command: 'vitest run --passWithNoTests'
    deps:
      - '^:build'
    inputs:
      - '**/*'
